### ISSUE TITLE
Allow configuring settings that are prefixes of other settings

### ISSUE THREAD

**Issue by dehnert** [kcr/snipe#50]
If I use M-= to configure `log.write`, `log.write_interval` is the default completion. If I hit enter having typed `log.write`, I appear to be configuring `log.write_interval` instead of `log.write`. It isn't obvious how I'd set `log.write`, if it's even possible.

**Comment by kcr** [comment]
Hit ^s until "log.write" swaps into the "this is what you are autocompleting to" slot.
So,

• There need to be more UI affordances around the completion cycling
• ^S should be in the cheatsheet while you're completing
• the completion set should probably have shorter things first (should probably just be sorted)

**Comment by kcr** [comment]
Oh or ^j to take the value without completing.

**Comment by kcr** [comment]
There is in fact code to augment the cheatsheet when completing but it's broken somewhere.
